services:
  # Serviço do Banco de Dados
  db:
    image: mysql:8.0
    container_name: mysql_bookstore
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_DATABASE: BookStore
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 10s
      retries: 10

  # Serviço API
  api:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: bookstore_api
    restart: on-failure
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "5000:8080"
    environment:
      - ConnectionStrings__DefaultConnection=Server=db;Database=BookStore;User=root;Password=admin;
      - ASPNETCORE_ENVIRONMENT=Development

volumes:
  mysql_data: